name: 'imf_project'
version: '1.0.0'
config-version: 2

profile: 'imf_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]


target-path: "target"
clean-targets: ["target", "dbt_modules", "logs"]

models:
  imf_project:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table


vars:

  overheating_inflation_threshold: 10    # High inflation with growth
  stagflation_inflation_threshold: 5     # High inflation with recession
  deflation_inflation_threshold: 2       # Low inflation with recession
  unemployment_threshold: 10             # High unemployment
  
  start_year: 2020
  end_year: 2024
