imf_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: xiaolong
      password: xiaolong
      port: 5433
      dbname: imf_data
      schema: dbt
      threads: 4
