version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-imf
    environment:
      POSTGRES_DB: imf_data
      POSTGRES_USER: xiaolong
      POSTGRES_PASSWORD: xiaolong
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imf-network

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - imf-network

networks:
  imf-network:
    driver: bridge

volumes:
  postgres_data: 